---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-bucketer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-bucketer
  template:
    metadata:
      labels:
        app: budget-bucketer
    spec:
      containers:
      - name: budget-bucketer
        image: berrydockerregistry:5000/budget-bucketer:0a21090b7c41e73000bb9e4195ca87f5251ccf34
        ports:
        - name: http
          containerPort: 10000