---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-bucketer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-bucketer
  template:
    metadata:
      labels:
        app: budget-bucketer
    spec:
      containers:
      - name: budget-bucketer
        image: walrusu/azurecalifornium:navy-snail-039896b669fe480bb653b9e9447361fcce72e6d4
        ports:
        - name: http
          containerPort: 3000
      imagePullSecrets:
        - name: regcred