---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-bucketer
spec:
  selector:
    matchLabels:
      app: budget-bucketer
  template:
    metadata:
      labels:
        app: budget-bucketer
    spec:
      containers:
      - name: budget-bucketer
        image: berrydockerregistry:5000/budget-bucketer:9a6cc47d083f93c9294a9d19a404b0d9249c7426
        ports:
        - name: http
          containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: budget-bucketer
spec:
  loadBalancerIP: 192.168.1.250
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: budget-bucketer
  type: LoadBalancer