---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-bucketer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-bucketer
  template:
    metadata:
      labels:
        app: budget-bucketer
    spec:
      containers:
      - name: budget-bucketer
        image: walrusu/azurecalifornium:navy-snail-b0f0389d4f8556e143949aec2bc27811733fcca8
        ports:
        - name: http
          containerPort: 3000
      imagePullSecrets:
        - name: regcred