---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-bucketer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-bucketer
  template:
    metadata:
      labels:
        app: budget-bucketer
    spec:
      containers:
      - name: budget-bucketer
        image: docker-registry:5000/budget-bucketer:5ce99fe9d77d9104d0f2ee12c71b234813c60a37
        ports:
        - name: http
          containerPort: 10000