---
apiVersion: v1
kind: Service
metadata:
  name: budget-bucketer-service
spec:
  loadBalancerIP: 192.168.1.221
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: budget-bucketer
  type: LoadBalancer