---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  loadBalancerIP: 192.168.1.223
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer