---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: goji
    path: "/srv/nfs/kubernetes/grafana/dashboards"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboards-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: goji
    path: "/srv/nfs/kubernetes/grafana/dashboards_config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboards-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-datasources-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: goji
    path: "/srv/nfs/kubernetes/grafana/datasources"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-datasources-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: goji
    path: "/srv/nfs/kubernetes/grafana/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi