---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  loadBalancerIP: 192.168.1.243
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer