---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  loadBalancerIP: 192.168.1.241
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: registry
  type: LoadBalancer