---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: screen-time-reward-chart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screen-time-reward-chart
  template:
    metadata:
      labels:
        app: screen-time-reward-chart
    spec:
      containers:
        - name: screen-time-reward-chart
          image: berrydockerregistry:5000/screen-time-reward-chart:0.0.2
          ports:
          - name: http
            containerPort: 8080
