---
apiVersion: v1
kind: Service
metadata:
  name: screen-time-reward-chart-service
spec:
  loadBalancerIP: 192.168.1.232
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: screen-time-reward-chart
  type: LoadBalancer