---
apiVersion: v1
kind: Service
metadata:
  name: very-good-purchase-service
spec:
  loadBalancerIP: 192.168.1.230
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: very-good-purchase
  type: LoadBalancer