---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookbook
  template:
    metadata:
      labels:
        app: cookbook
    spec:
      containers:
      - name: cookbook
        image: berrydockerregistry:5000/cookbook:c66e354c2e70e33e4aade0fdb651745a9e0fe427
        ports:
        - name: http
          containerPort: 10000